"""initial trustvault schema

Revision ID: 47e0f89d5d21
Revises: 
Create Date: 2026-05-17 22:12:52.972134
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '47e0f89d5d21'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=200), nullable=True),
    sa.Column('session_id', sa.String(length=200), nullable=True),
    sa.Column('tenant_id', sa.String(length=200), nullable=True),
    sa.Column('raw_query', sa.Text(), nullable=True),
    sa.Column('structured_query', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result_count', sa.Integer(), nullable=True),
    sa.Column('entity_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('object_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('search_source', sa.String(length=100), nullable=True),
    sa.Column('ai_used', sa.Boolean(), nullable=False),
    sa.Column('ai_provider', sa.String(length=100), nullable=True),
    sa.Column('ai_model', sa.String(length=150), nullable=True),
    sa.Column('export_path', sa.Text(), nullable=True),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('correlation_id', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_correlation_id'), 'audit_events', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_audit_events_event_type'), 'audit_events', ['event_type'], unique=False)
    op.create_table('completeness_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('rule_key', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('document_type', sa.String(length=150), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('matched_evidence_object_id', sa.String(length=100), nullable=True),
    sa.Column('details_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_completeness_results_entity_id'), 'completeness_results', ['entity_id'], unique=False)
    op.create_index(op.f('ix_completeness_results_run_id'), 'completeness_results', ['run_id'], unique=False)
    op.create_table('completeness_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('ruleset_id', sa.UUID(), nullable=True),
    sa.Column('container_version_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('required_count', sa.Integer(), nullable=False),
    sa.Column('present_count', sa.Integer(), nullable=False),
    sa.Column('missing_count', sa.Integer(), nullable=False),
    sa.Column('result_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_completeness_runs_entity_id'), 'completeness_runs', ['entity_id'], unique=False)
    op.create_table('entities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=300), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entities_external_id'), 'entities', ['external_id'], unique=True)
    op.create_table('entity_container_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('storage_uri', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('evidence_object_count', sa.Integer(), nullable=False),
    sa.Column('manifest_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('hash_report_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by_job_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id', 'version_number', name='uq_entity_container_version')
    )
    op.create_index(op.f('ix_entity_container_versions_entity_id'), 'entity_container_versions', ['entity_id'], unique=False)
    op.create_table('evidence_objects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('object_type', sa.String(length=100), nullable=False),
    sa.Column('source_system', sa.String(length=150), nullable=False),
    sa.Column('storage_uri', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('content_type', sa.String(length=150), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_objects_entity_id'), 'evidence_objects', ['entity_id'], unique=False)
    op.create_table('extraction_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('evidence_object_id', sa.String(length=100), nullable=True),
    sa.Column('extraction_type', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('result_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extraction_events_entity_id'), 'extraction_events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_extraction_events_evidence_object_id'), 'extraction_events', ['evidence_object_id'], unique=False)
    op.create_table('fits_index_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('container_version_id', sa.UUID(), nullable=False),
    sa.Column('evidence_object_id', sa.String(length=100), nullable=True),
    sa.Column('hdu_name', sa.String(length=100), nullable=False),
    sa.Column('filename', sa.String(length=300), nullable=True),
    sa.Column('object_type', sa.String(length=100), nullable=True),
    sa.Column('source_system', sa.String(length=150), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('text_content', sa.Text(), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fits_index_entries_container_version_id'), 'fits_index_entries', ['container_version_id'], unique=False)
    op.create_index(op.f('ix_fits_index_entries_entity_id'), 'fits_index_entries', ['entity_id'], unique=False)
    op.create_index(op.f('ix_fits_index_entries_evidence_object_id'), 'fits_index_entries', ['evidence_object_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.String(length=200), nullable=True),
    sa.Column('correlation_id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_correlation_id'), 'jobs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_jobs_job_type'), 'jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_table('licence_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('licence_id', sa.String(length=200), nullable=True),
    sa.Column('customer_name', sa.String(length=300), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('modules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('valid_until', sa.String(length=30), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('retention_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('retention_class', sa.String(length=100), nullable=False),
    sa.Column('retention_years', sa.Integer(), nullable=False),
    sa.Column('legal_hold_default', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ruleset_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ruleset_id', sa.UUID(), nullable=False),
    sa.Column('rule_key', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('document_type', sa.String(length=150), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('applies_when_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('max_age_days', sa.Integer(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ruleset_rules_ruleset_id'), 'ruleset_rules', ['ruleset_id'], unique=False)
    op.create_table('rulesets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_systems',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('system_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('external_subject', sa.String(length=300), nullable=False),
    sa.Column('email', sa.String(length=300), nullable=True),
    sa.Column('display_name', sa.String(length=300), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('roles', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('external_subject')
    )
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('value_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('value_type', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.Column('is_editable', sa.Boolean(), nullable=False),
    sa.Column('updated_by_user_id', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_foreign_key('fk_evidence_objects_entity_id_entities', 'evidence_objects', 'entities', ['entity_id'], ['id'])
    op.create_foreign_key('fk_entity_container_versions_entity_id_entities', 'entity_container_versions', 'entities', ['entity_id'], ['id'])
    op.create_foreign_key('fk_fits_index_entries_entity_id_entities', 'fits_index_entries', 'entities', ['entity_id'], ['id'])
    op.create_foreign_key('fk_fits_index_entries_container_version_id_entity_container_versions', 'fits_index_entries', 'entity_container_versions', ['container_version_id'], ['id'])
    op.create_foreign_key('fk_ruleset_rules_ruleset_id_rulesets', 'ruleset_rules', 'rulesets', ['ruleset_id'], ['id'])
    op.create_foreign_key('fk_completeness_runs_entity_id_entities', 'completeness_runs', 'entities', ['entity_id'], ['id'])
    op.create_foreign_key('fk_completeness_runs_ruleset_id_rulesets', 'completeness_runs', 'rulesets', ['ruleset_id'], ['id'])
    op.create_foreign_key('fk_completeness_runs_container_version_id_entity_container_versions', 'completeness_runs', 'entity_container_versions', ['container_version_id'], ['id'])
    op.create_foreign_key('fk_completeness_results_run_id_completeness_runs', 'completeness_results', 'completeness_runs', ['run_id'], ['id'])
    op.create_foreign_key('fk_completeness_results_entity_id_entities', 'completeness_results', 'entities', ['entity_id'], ['id'])
    op.create_foreign_key('fk_extraction_events_entity_id_entities', 'extraction_events', 'entities', ['entity_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_extraction_events_entity_id_entities', 'extraction_events', type_='foreignkey')
    op.drop_constraint('fk_completeness_results_entity_id_entities', 'completeness_results', type_='foreignkey')
    op.drop_constraint('fk_completeness_results_run_id_completeness_runs', 'completeness_results', type_='foreignkey')
    op.drop_constraint('fk_completeness_runs_container_version_id_entity_container_versions', 'completeness_runs', type_='foreignkey')
    op.drop_constraint('fk_completeness_runs_ruleset_id_rulesets', 'completeness_runs', type_='foreignkey')
    op.drop_constraint('fk_completeness_runs_entity_id_entities', 'completeness_runs', type_='foreignkey')
    op.drop_constraint('fk_ruleset_rules_ruleset_id_rulesets', 'ruleset_rules', type_='foreignkey')
    op.drop_constraint('fk_fits_index_entries_container_version_id_entity_container_versions', 'fits_index_entries', type_='foreignkey')
    op.drop_constraint('fk_fits_index_entries_entity_id_entities', 'fits_index_entries', type_='foreignkey')
    op.drop_constraint('fk_entity_container_versions_entity_id_entities', 'entity_container_versions', type_='foreignkey')
    op.drop_constraint('fk_evidence_objects_entity_id_entities', 'evidence_objects', type_='foreignkey')
    op.drop_table('app_settings')
    op.drop_table('users')
    op.drop_table('source_systems')
    op.drop_table('rulesets')
    op.drop_index(op.f('ix_ruleset_rules_ruleset_id'), table_name='ruleset_rules')
    op.drop_table('ruleset_rules')
    op.drop_table('retention_policies')
    op.drop_table('licence_status')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_job_type'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_correlation_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_fits_index_entries_evidence_object_id'), table_name='fits_index_entries')
    op.drop_index(op.f('ix_fits_index_entries_entity_id'), table_name='fits_index_entries')
    op.drop_index(op.f('ix_fits_index_entries_container_version_id'), table_name='fits_index_entries')
    op.drop_table('fits_index_entries')
    op.drop_index(op.f('ix_extraction_events_evidence_object_id'), table_name='extraction_events')
    op.drop_index(op.f('ix_extraction_events_entity_id'), table_name='extraction_events')
    op.drop_table('extraction_events')
    op.drop_index(op.f('ix_evidence_objects_entity_id'), table_name='evidence_objects')
    op.drop_table('evidence_objects')
    op.drop_index(op.f('ix_entity_container_versions_entity_id'), table_name='entity_container_versions')
    op.drop_table('entity_container_versions')
    op.drop_index(op.f('ix_entities_external_id'), table_name='entities')
    op.drop_table('entities')
    op.drop_index(op.f('ix_completeness_runs_entity_id'), table_name='completeness_runs')
    op.drop_table('completeness_runs')
    op.drop_index(op.f('ix_completeness_results_run_id'), table_name='completeness_results')
    op.drop_index(op.f('ix_completeness_results_entity_id'), table_name='completeness_results')
    op.drop_table('completeness_results')
    op.drop_index(op.f('ix_audit_events_event_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_correlation_id'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
